name: fog_gen_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.8+11

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  toastification: ^3.0.3
  logger: ^2.6.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  drift: ^2.29.0
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_switch: ^0.3.2
  sqlite3_flutter_libs: ^0.5.40
  flutter_slidable: ^4.0.3
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  video_player: ^2.10.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.4.11

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500
        - asset: assets/fonts/montserrat_semibold.ttf
          weight: 600
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700
